const tutorialesData = {
  "categorias": [
    {
      "nombre": "Tutorial De FL Studio 12",
      "tutoriales": [
        { "titulo": "1.- Introducción a FL Studio 12", "id_youtube": "Zm4cvtf69jA" },
        { "titulo": "2.- Secuenciación de Pasos en FL Studio 12", "id_youtube": "h52lRKck0r4" },
        { "titulo": "3.- Mejora de Sonidos y Eliminación de Frecuencias no Deseadas en FL Studio 12", "id_youtube": "SS5JnrilsWw" },
        { "titulo": "4.- Explorando el Piano Roll en FL Studio 12", "id_youtube": "4Nt68yUnwbY" },
        { "titulo": "5.- Profundizando en el Mezclador de FL Studio 12", "id_youtube": "m1GP8fs0K6c" },
        { "titulo": "6.- Navegando el Explorador de Archivos (Browser) en FL Studio 12", "id_youtube": "SWL28YLfwz8" },
        { "titulo": "7.- Creatividad con Patrones en FL Studio 12", "id_youtube": "XWDsGtF1oWQ" },
        { "titulo": "8.- Ampliando tus Posibilidades: Añadiendo Plugins en FL Studio 12", "id_youtube": "-dyhA-A6cHo" },
        { "titulo": "9.- Capturando tu Inspiración: Grabación MIDI en FL Studio 12", "id_youtube": "nuvlFD7rp6Q" },
        { "titulo": "10.- Ritmos Calientes: Creación de Baterías de Reggaeton en FL Studio 12", "id_youtube": "sGXHabJ-iLo" },
        { "titulo": "11.- La Magia de la Exportación de Alta Calidad en FL Studio 12", "id_youtube": "viR1rAUInFU" },
        { "titulo": "12.- Agregando Sabores al Playlist: Loops y Samples en FL Studio 12", "id_youtube": "A0VB4OK4ma4" },
        { "titulo": "13.- Sincronización Perfecta: Ajustando el Tempo de tus Loops en FL Studio 12", "id_youtube": "oOsVkUjpNmg" },
        { "titulo": "14.- Optimizando la Precisión con ACT Timebase PPQ en FL Studio 12", "id_youtube": "e61ds3vFiAo" },
        { "titulo": "15.- Expande tu Creatividad con el Mapa de Progresiones ACT - Fl Studio 12", "id_youtube": "Kvh3dBhchGc" },
        { "titulo": "16.- VST Plug-ins más Utilizados en el Género - Fl Studio 12", "id_youtube": "aatUH3ZZgnU" },
        { "titulo": "17.- Consejos y Trucos para Brillar en FL Studio 12", "id_youtube": "WIUVEi17Gfc" },
        { "titulo": "18.- Efectos Potentes: Los VST Plug-Ins más Populares - Fl Studio 12", "id_youtube": "JDLmDhNlc0I" },
        { "titulo": "19.- Ecualizador: Funcionamiento y Utilidad Explicados - Fl Studio 12", "id_youtube": "Eqq-Gzjr-zA" },
        { "titulo": "20.- Compresor: Uso Efectivo y Aplicaciones en la Música - Fl Studio 12", "id_youtube": "WqC8FxYKkxY" },
        { "titulo": "21.- Configuración Perfecta de MIDI en FL Studio 12", "id_youtube": "_F27mXF1GjU" },
        { "titulo": "22.- Extracción de Tiempo de una Acapella - Fl Studio 12", "id_youtube": "TQzQMbjOapg" },
        { "titulo": "23.- Creando Potentes Baterías de Rap en FL Studio 12", "id_youtube": "NBu20_t8bcc" },
        { "titulo": "24.- Dominando el Bajo 808 con ACT: Potencia Garantizada - Fl Studio 12", "id_youtube": "ULpqX2DHkcM" },
        { "titulo": "25.- Cómo Crear Baterías de Dancehall en Fl Studio 12", "id_youtube": "plzy_bNUitI" },
        { "titulo": "26.- Añadiendo Energía al Dembow: Técnicas Avanzadas - Fl Studio 12", "id_youtube": "ZvG7K3__Nd8" },
        { "titulo": "27.- Creando Baterías de Reggaeton Estilo Colombiano (Mode UP) - Fl Studio 12", "id_youtube": "XSpDLRg-_dU" },
        { "titulo": "28.- Mezcla Creativa: Fusionando Loops para Nuevos Horizontes - Fl Studio 12", "id_youtube": "ZqCka3sKXa4" },
        { "titulo": "29.- Side-Chain Maestro: Aplicación Perfecta en tus Sonidos - Fl Studio 12", "id_youtube": "3uXc2cxf8XE" },
        { "titulo": "30.- Automatización de Clips: Controla Cambios Dinámicos - Fl Studio 12", "id_youtube": "tW3_lCqqIPw" },
        { "titulo": "31.- Efecto Tape Stop: Dando un Toque Único a tu Producción - Fl Studio 12", "id_youtube": "Swh0CkLUKAs" },
        { "titulo": "32.- Mixer Organizado: Canalización Profesional de Sonidos - Fl Studio 12", "id_youtube": "hAVcGXPADZk" },
        { "titulo": "33.- Cortando Loops para Progresiones Innovadoras - Fl Studio 12", "id_youtube": "Ozcf4onCTVA" },
        { "titulo": "34.- Como Salvar una Cadena de Efectos en el Mixer en Fl Studio 12", "id_youtube": "n2i0ox7-Erk" },
        { "titulo": "35.- Transformando el Tono de un Loop o Sample: Paso a Paso - Fl Studio 12", "id_youtube": "qzfA_YVNIrE" },
        { "titulo": "36.- Marcando Momentos Importantes: Agregando Markers - Fl Studio 12", "id_youtube": "J__aa_IjSWU" },
        { "titulo": "37.- Duplicando Patrones: Más Efectividad en tu Trabajo - Fl Studio 12", "id_youtube": "QiEKTQUr1C0" },
        { "titulo": "38.- Limpiando un Proyecto de FL Studio: Mantén tu Espacio Ordenado", "id_youtube": "WgaoFPFUCF4" },
        { "titulo": "39.- Crear una Pista de Reggaetón: Parte 1 - Comenzando - Fl Studio 12", "id_youtube": "LO14-rjke0k" },
        { "titulo": "40.- Crear una Pista de Reggaetón: Parte 2 - Avanzando - Fl Studio 12", "id_youtube": "mrj7ElJcgCo" },
        { "titulo": "41.- Crear una Pista de Reggaetón: Parte 3 - Perfeccionando - Fl Studio 12", "id_youtube": "yrUB__7yOM8" },
        { "titulo": "42.- Crear una Pista de Reggaetón: Parte 4 - Brillando - Fl Studio 12", "id_youtube": "X9hc-3MCw_s" },
        { "titulo": "43.- Crear una Pista de Rap-Trap: Parte 1 - Los Fundamentos - Fl Studio 12", "id_youtube": "UgXogF2kA-M" },
        { "titulo": "44.- Crear una Pista de Rap-Trap: Parte 2 - Elevando el Nivel - Fl Studio 12", "id_youtube": "1q-y23wrOq4" },
        { "titulo": "45.- Crear una Pista de Rap-Trap: Parte 3 - Detalles Impactantes - Fl Studio 12", "id_youtube": "V9MjiW7_CZ8" },
        { "titulo": "46.- Exportación Profesional: Pistas por Canales Separados - Fl Studio 12", "id_youtube": "wmyQxXwBRN4" },
        { "titulo": "47.- Crear una Pista de Dancehall: Parte 1 - Fl Studio 12", "id_youtube": "mm1ndpyrI6M" },
        { "titulo": "48.- Crear una Pista de Dancehall: Parte 2 - Fl Studio 12", "id_youtube": "M8pRhhOrrGI" },
        { "titulo": "49.- Crear una Pista de Dancehall: Parte 3 - Fl Studio 12", "id_youtube": "3-WslD-go8s" },
        { "titulo": "50.- Explorando una Pista en Profundidad - Parte 1 - Fl Studio 12", "id_youtube": "5A7iABIkKqc" },
        { "titulo": "51.- Explorando una Pista en Profundidad - Parte 2 - Fl Studio 12", "id_youtube": "VZ6WBhY5Zcg" },
        { "titulo": "52.- Explorando una Pista en Profundidad - Parte 3 - Fl Studio 12", "id_youtube": "XGDn_Qgdgj8" },
        { "titulo": "53.- Explorando una Pista en Profundidad - Parte 4 - Fl Studio 12", "id_youtube": "xfjuNm1Fc0w" },
        { "titulo": "54.- Explorando una Pista en Profundidad - Parte 5 - Fl Studio 12", "id_youtube": "d7W7ocFUkKg" }
      ]
    },
    {
      "nombre": "Producción y Edición de Ritmos Urbanos",
      "tutoriales": [
        { "titulo": "Dembow Dominicano: Ritmos Profesionales desde Cero", "id_youtube": "5TbNCFx-hdU" },
        { "titulo": "Producción de Trap: Fundamentos y Técnicas Avanzadas", "id_youtube": "6s6hxeliMSY" },
        { "titulo": "Bases Urbanas: Creando Ritmos Modernos y Potentes", "id_youtube": "DKJeQ5U9JVU" },
        { "titulo": "Reggaeton y Old School", "id_youtube": "5RZSNoxSn84" },
        { "titulo": "Pop Urbano: El Sonido Moderno", "id_youtube": "TlnQgBA-oiQ" },
        { "titulo": "Afrobeat: Ritmos Africanos y Urbanos", "id_youtube": "pYdEnwvwFTA" },
        { "titulo": "Aleteo: Ritmo y Estilo", "id_youtube": "lbE-mq0AsJg" },
        { "titulo": "Funk: Groove y Ritmo", "id_youtube": "-uCCc5gsmdg" },
        { "titulo": "Trap: Producción y Estructura", "id_youtube": "uDJF1s-L0DI" },
        { "titulo": "EDM: Energía en tus Pistas", "id_youtube": "-FPVFIJC7Ys" },
        { "titulo": "Taller de Reggaetón Flow", "id_youtube": "FYEhEklQvsc" }
      ]
    },
    {
      "nombre": "Técnicas de Mezcla y Mastering",
      "tutoriales": [
        { "titulo": "Mezcla y Mastering en Dembow: Limpiando el Dembow: De Caos a Claridad", "id_youtube": "EDRRZSIp05k" },
        { "titulo": "Mezcla y Mastering en Dembow: Percusiones Individuales: Cortando y Editando Ritmos", "id_youtube": "htSCQ2heZn0" },
        { "titulo": "Mezcla y Mastering en Dembow: Organiza tu Mezcla: Asignando Canales a cada Percusión", "id_youtube": "s4PkiCs5fV8" },
        { "titulo": "Mezcla y Mastering en Dembow: Estructura de Ganancia: El Primer Paso para una Mezcla Profesional", "id_youtube": "EnADrIfJ1YI" },
        { "titulo": "Mezcla y Mastering en Dembow: Procesando el Kick: Consigue Pegada y Punch", "id_youtube": "2ZfansSosns" },
        { "titulo": "Mezcla y Mastering en Dembow: Procesando Hi-Hats y Snare: Define tus Ritmos", "id_youtube": "fe-s8YrmSi4" },
        { "titulo": "Mezcla y Mastering en Dembow: Procesando el Snare: Dale Presencia y Carácter", "id_youtube": "BLZ_BKng4MQ" },
        { "titulo": "Mezcla y Mastering en Dembow: Procesando Kick 2: Más Potencia para tu Dembow", "id_youtube": "Iv_XmL0LkCs" },
        { "titulo": "Mezcla y Mastering en Dembow: Balance de Percusiones: Logra un Groove Perfecto", "id_youtube": "KKxiEOzYL-I" },
        { "titulo": "Mezcla y Mastering en Dembow: Mezclando el Dembow Completo: Uniendo los Ritmos", "id_youtube": "OqTJK3JgxUw" },
        { "titulo": "Mezcla y Mastering en Dembow: Probando el Dembow: Análisis del Resultado Final", "id_youtube": "14wi2vH0Q4E" },
        { "titulo": "Mastering Final: Mastering Profesional: Convierte tu Mezcla en un Éxito", "id_youtube": "Vfy9L8xhaFE" },
        { "titulo": "Mastering Final: Mastering Profesional: Parte 1", "id_youtube": "VQmg8QzdBt4" },
        { "titulo": "Mastering Final: Mastering Profesional: Parte 2", "id_youtube": "m3NosXMYf08" },
        { "titulo": "Mastering Final: Mastering: El Poder del Maximizer", "id_youtube": "7J2TZSOkdQM" },
        { "titulo": "Mastering Final: Mastering: EQ Final", "id_youtube": "qRMbGMZdKTA" },
        { "titulo": "Mastering Final: Mastering: Harmonic Exciter para Brillo Extra", "id_youtube": "4jyO58td1os" }
      ]
    },
    {
      "nombre": "Edición y Producción por Género Musical",
      "tutoriales": [
        { "titulo": "Reggaeton: Cómo Crear un Edit de Reggaetón", "id_youtube": "nsAXU43mM9E" },
        { "titulo": "Rock: Cómo Crear un Edit de Rock", "id_youtube": "PDI6lbXUnek" },
        { "titulo": "Rock: Producción de Guitarras y Baterías", "id_youtube": "Psky57pxBG4" },
        { "titulo": "Rock II: Mezcla y Masterización", "id_youtube": "SFHzIrit7U0" },
        { "titulo": "Electrónica: Cómo Crear un Edit de Electrónica", "id_youtube": "Fu-aZrzrZH4" },
        { "titulo": "Electrónica: Taller Tech House", "id_youtube": "QyDSe-Qd1PU" },
        { "titulo": "Cumbia: Cómo Crear un Edit de Cumbia", "id_youtube": "h_43DVKfWi4" },
        { "titulo": "Cumbia: Cumbia Uruguaya: Producción y Ritmos", "id_youtube": "RXfAmLjQ9aU" },
        { "titulo": "Salsa: Cómo Crear un Edit de Salsa", "id_youtube": "OO2Mtkwsab4" },
        { "titulo": "Salsa: Ritmo y Producción", "id_youtube": "V3P_0h8chRQ" },
        { "titulo": "Salsa: Salsa Old Clásica: Sonidos Vintage", "id_youtube": "p0HkSPFEyAU" },
        { "titulo": "Música Latina: Cómo Crear un Edit de Latin Merengue", "id_youtube": "woAiXUaInYk" },
        { "titulo": "Música Latina: Latin Mambo y Merengue Electrónico", "id_youtube": "YOG5yimAYz4" }
      ]
    },
    {
      "nombre": "Guía de Efectos y Herramientas",
      "tutoriales": [
        { "titulo": "EQ y Compresión: Ecualización Práctica: Moldea tu Sonido", "id_youtube": "Avq7tt6F1Gw" },
        { "titulo": "EQ y Compresión: EQ: La Guía Definitiva para la Ecualización", "id_youtube": "8EkNrNZI71w" },
        { "titulo": "EQ y Compresión: Dominando la Compresión: Dale Pegada a tus Tracks", "id_youtube": "BjxGJfyoGUM" },
        { "titulo": "EQ y Compresión: EQ Eight: Ecualización Profesional", "id_youtube": "nO-6_0n1ifk" },
        { "titulo": "EQ y Compresión: EQ Three: Controla Frecuencias en Tres Bandas", "id_youtube": "dZkVjBOPQEM" },
        { "titulo": "EQ y Compresión: EQ en Bases: Dale Claridad a tu Ritmo", "id_youtube": "Nc2rWMsJPLg" },
        { "titulo": "EQ y Compresión: Compresión: Control de Dinámicas", "id_youtube": "qzgNi9PuRXA" },
        { "titulo": "EQ y Compresión: Compresión Multibanda y Sidechain", "id_youtube": "R4h19bJgsIk" },
        { "titulo": "Delay y Reverb: Reverb y Delay: Efectos Espaciales", "id_youtube": "83-6h8gicHY" },
        { "titulo": "Delay y Reverb: Ping Pong Delay: Sonido Espacial y Dinámico", "id_youtube": "3S2QeH0cs6s" },
        { "titulo": "Delay y Reverb: Reverb: El Espacio de tu Sonido", "id_youtube": "tQqYIykbpbI" },
        { "titulo": "Delay y Reverb: Simple Delay: Efectos Clásicos", "id_youtube": "Ih_iqyhaJhI" },
        { "titulo": "Otros Efectos: Auto Filter: Crea Movimiento y Texturas en tu Música", "id_youtube": "RBfFSG-UPoM" },
        { "titulo": "Otros Efectos: Auto Pan: Crea Efectos Estéreo", "id_youtube": "b9kDLXCgn9U" },
        { "titulo": "Otros Efectos: Beat Repeat: Ritmo y Glitch Creativo", "id_youtube": "_5CskFRIbh8" },
        { "titulo": "Otros Efectos: Filter Delay: Añade Textura y Profundidad", "id_youtube": "1whhmM_GqGk" },
        { "titulo": "Otros Efectos: Gate: Limpia el Ruido de tus Grabaciones", "id_youtube": "ZhjVCt-Igoc" },
        { "titulo": "Otros Efectos: Saturator: Color y Armónicos en tu Audio", "id_youtube": "Frbsa8V72Bc" },
        { "titulo": "Otros Efectos: Distorsión: Añade Carácter y Suciedad", "id_youtube": "9qC2GeNRqUY" }
      ]
    },
    {
      "nombre": "Fundamentos y Flujo de Trabajo",
      "tutoriales": [
        { "titulo": "Introducción: De la Teoría a la Práctica: Aplicando lo Aprendido", "id_youtube": "epCd9Obmbts" },
        { "titulo": "Introducción: Masterclass: Resuelve tus Dudas de Producción Musical", "id_youtube": "R0A4E0t_wQQ" },
        { "titulo": "Introducción: Introducción", "id_youtube": "gNvZerFYKKg" },
        { "titulo": "Introducción: Introducción al Curso", "id_youtube": "uUXZ4iiUvoE" },
        { "titulo": "Introducción: Introducción: Configuración y Preferencias", "id_youtube": "uN81SN8ziJE" },
        { "titulo": "Introducción: Fundamentos de la Producción Musical", "id_youtube": "r5-TkBjnLx4" },
        { "titulo": "Introducción: Introducción al Ableton Live", "id_youtube": "6nNBwpvaS44" },
        { "titulo": "Creación de Bases: El Arte de la Creación de Bases", "id_youtube": "-RJIKuHcm_g" },
        { "titulo": "Creación de Bases: De la Idea a la Pista", "id_youtube": "Zrzhn3Ijwp0" },
        { "titulo": "Creación de Bases: Trabajando con Audio", "id_youtube": "7KtgtwXOGSM" },
        { "titulo": "Creación de Bases: Potencia el MIDI", "id_youtube": "q5p5HC-8ggE" },
        { "titulo": "Warpeo: El Arte del Warp: Sincroniza y Manipula Audio", "id_youtube": "zHvjfUqoS-0" },
        { "titulo": "Warpeo: Warpeo Avanzado: Sincroniza Temas con Ritmos Regulares e Irregulares", "id_youtube": "GzU-ZCQDWjw" },
        { "titulo": "Warpeo: Warpeo y Trucos de Edición en Ableton Live", "id_youtube": "yeqG03NERkA" },
        { "titulo": "Warpeo: Warp: Sincroniza Temas Regulares", "id_youtube": "EqRB5lf0gTs" },
        { "titulo": "Warpeo: Warp: Domina Ritmos Irregulares", "id_youtube": "ejwyppToWWc" },
        { "titulo": "Warpeo: Tipos de Warp: Elige el Mejor para Cada Pista", "id_youtube": "TwpiOwtxk2s" },
        { "titulo": "Técnicas de Edición: Dominando las Transiciones: Subidas, Bajadas y Acapellas", "id_youtube": "S4De9jUJz7I" },
        { "titulo": "Técnicas de Edición: Pases y Cambios de Ritmo: Transiciones Suaves y Creativas", "id_youtube": "OIv29-MYiJg" },
        { "titulo": "Técnicas de Edición: Efectos en la Mezcla: Dale Color y Textura a tu Música", "id_youtube": "FRepG0NUBvY" },
        { "titulo": "Técnicas de Edición: EQ Final: El Toque Profesional en tus Mezclas", "id_youtube": "Wey_b1NYvu0" },
        { "titulo": "Técnicas de Edición: Mezcla en Ableton: Creando Mixes", "id_youtube": "j9_E1GwYHIo" },
        { "titulo": "Técnicas de Edición: Layering: El Arte de las Capas", "id_youtube": "R1McLc4qj-s" },
        { "titulo": "Técnicas de Edición: Loops: Volumen y Paneo Creativo", "id_youtube": "uruGKkIsqio" },
        { "titulo": "Técnicas de Edición: Spectrum: Analiza tu Sonido", "id_youtube": "4rB4VahVyx4" }
      ]
    }
  ]
};